"""Pure shape/slice contract shared across the two Brax environments."""

BASE_OBS_DIM = 101
BUFFER_FRAMES = 16
FEATURE_DIM = 60
ACTION_DIM = 10
PHASE_DIM = 4
PLAN_DIM = 16
COMMAND_DIM = 3

FEATURE_BUFFER_SLICE = slice(BASE_OBS_DIM, BASE_OBS_DIM + BUFFER_FRAMES * FEATURE_DIM)
PREVIOUS_CONTROL_SLICE = slice(
    FEATURE_BUFFER_SLICE.stop, FEATURE_BUFFER_SLICE.stop + ACTION_DIM
)
PHASE_SLICE = slice(
    PREVIOUS_CONTROL_SLICE.stop, PREVIOUS_CONTROL_SLICE.stop + PHASE_DIM
)
PLAN_SLICE = slice(PHASE_SLICE.stop, PHASE_SLICE.stop + PLAN_DIM)
COMMAND_SLICE = slice(PLAN_SLICE.stop, PLAN_SLICE.stop + COMMAND_DIM)
OBS_DIM = COMMAND_SLICE.stop
