"""Held-out SSL gate for the frozen Demo B action-conditioned transition.

The target is generated by shifting a real continuous recording. Skill is normalized
against the honest latent-persistence null; raw latent MSE is never the verdict.
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path

import numpy as np
import torch
import h5py

from canvas.prepare import motion_features, quat2yaw
from demo_c.motor import H, K, FrozenMotor
from demo_c.neural_data import DEFAULT_SESSIONS, REGION, session_path
from demo_c.neural_eval import BLOCK_TOKENS, GAP_TOKENS
from demo_c.train_world import locomotion_starts

OUT = Path(__file__).resolve().parent / "out" / "world_validation"


def root_command(xy0, yaw0, xy1, yaw1):
    delta = xy1 - xy0
    c, s = np.cos(-yaw0), np.sin(-yaw0)
    local = np.stack((c * delta[:, 0] - s * delta[:, 1], s * delta[:, 0] + c * delta[:, 1]), -1)
    turn = (yaw1 - yaw0 + np.pi) % (2 * np.pi) - np.pi
    return np.concatenate((local, turn[:, None]), -1).astype(np.float32)


@torch.inference_mode()
def evaluate_session(motor, session, max_windows=4096):
    # Match Demo B's training construction exactly: independently encode each real
    # contiguous 64-frame locomotion crop, then split its 16 tokens into H=8/K=8.
    # A continuous encoder stream is a different input distribution because training
    # crops deliberately contain causal left-padding at their first tokens.
    source = session_path(session)
    with h5py.File(source, "r") as file:
        qpos = file["/pose/qpos"][:].astype(np.float32)
        keypoints = file["/pose/keypoints"][:].astype(np.float32)
        behavior_ds = file["/behavior/motion_mapper"]
        behavior = behavior_ds[:]
        behavior_names = [
            x.decode() if isinstance(x, bytes) else str(x)
            for x in behavior_ds.attrs["names"]
        ]
    features = motion_features(qpos, keypoints)
    starts = locomotion_starts(qpos, behavior, behavior_names)
    token_start = starts // 4; block = token_start // BLOCK_TOKENS; within = token_start % BLOCK_TOKENS
    valid = (
        (block % 5 == 4)
        & (within >= GAP_TOKENS)
        & (within < BLOCK_TOKENS - GAP_TOKENS - (H + K))
    )
    starts = starts[valid]
    if not len(starts):
        raise ValueError(f"{session}: no held-out windows after the frozen split")
    if len(starts) > max_windows:
        rng = np.random.default_rng(20260719); starts = np.sort(rng.choice(starts, max_windows, replace=False))

    histories, targets, predictions = [], [], []
    yaw = quat2yaw(qpos[:, 3:7])
    command = root_command(qpos[starts + 32, :2], yaw[starts + 32], qpos[starts + 63, :2], yaw[starts + 63])
    offsets = np.arange(64)[None]
    for begin in range(0, len(starts), 512):
        chosen = starts[begin:begin + 512]
        clip = torch.as_tensor(features[chosen[:, None] + offsets], device=motor.device)
        clip = (clip - motor.norms["mmean"]) / motor.norms["mstd"]
        latent = motor.motion.encode(clip)[0]
        latent = (latent - motor.norms["zmean"]) / motor.norms["zstd"]
        hist_t, target_t = latent[:, :H], latent[:, H:H + K]
        cmd_t = torch.as_tensor(command[begin:begin + len(chosen)], device=motor.device)
        cmd_t = (cmd_t - motor.norms["cmean"]) / motor.norms["cstd"]
        histories.append(hist_t.cpu().numpy()); targets.append(target_t.cpu().numpy())
        predictions.append(motor.transition.predict(hist_t, cmd_t).cpu().numpy())
    history = np.concatenate(histories); target = np.concatenate(targets)
    prediction = np.concatenate(predictions)
    persistence = np.repeat(history[:, -1:, :], K, axis=1)
    model_mse = float(np.mean((prediction - target) ** 2))
    persistence_mse = float(np.mean((persistence - target) ** 2))
    per_horizon = np.mean((prediction - target) ** 2, axis=(0, 2))
    null_horizon = np.mean((persistence - target) ** 2, axis=(0, 2))
    finite = bool(np.isfinite(prediction).all())
    return {
        "session": session, "region": REGION[session.split("/", 1)[0]], "windows": len(starts),
        "model_mse": model_mse, "persistence_mse": persistence_mse,
        "skill_over_persistence": 1 - model_mse / persistence_mse,
        "finite": finite,
        "mse_by_token_horizon": per_horizon.tolist(),
        "persistence_mse_by_token_horizon": null_horizon.tolist(),
    }


def plot(rows, path):
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt
    fig, ax = plt.subplots(figsize=(5.5, 3.4), dpi=150)
    horizon = (np.arange(K) + 1) * 0.08
    model = np.mean([row["mse_by_token_horizon"] for row in rows], 0)
    null = np.mean([row["persistence_mse_by_token_horizon"] for row in rows], 0)
    ax.plot(horizon, null, "--", color="#888", label="persistence null")
    ax.plot(horizon, model, color="#4b9cc8", label="action-conditioned WAM")
    ax.set(xlabel="prediction horizon (s)", ylabel="normalized latent MSE", title="held-out real rodent transitions")
    ax.grid(alpha=.25); ax.legend(frameon=False); fig.tight_layout(); path.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(path); plt.close(fig)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--sessions", nargs="+", default=list(DEFAULT_SESSIONS))
    parser.add_argument("--max-windows", type=int, default=4096)
    parser.add_argument("--checkpoint", type=Path, default=None)
    args = parser.parse_args()
    motor = FrozenMotor("cuda" if torch.cuda.is_available() else "cpu", args.checkpoint)
    rows = []
    for session in args.sessions:
        row = evaluate_session(motor, session, args.max_windows); rows.append(row)
        print(
            f"{session}: mse={row['model_mse']:.4f} persistence={row['persistence_mse']:.4f} "
            f"skill={row['skill_over_persistence']:+.1%}", flush=True,
        )
    summary = {
        "skill_session_mean": float(np.mean([row["skill_over_persistence"] for row in rows])),
        "skill_session_sd": float(np.std([row["skill_over_persistence"] for row in rows], ddof=1)),
        "all_finite": all(row["finite"] for row in rows),
        "gate_pass": all(row["finite"] and row["skill_over_persistence"] > 0 for row in rows),
        "sessions": len(rows),
    }
    OUT.mkdir(parents=True, exist_ok=True)
    (OUT / "metrics.json").write_text(json.dumps({"summary": summary, "sessions": rows}, indent=2) + "\n")
    plot(rows, OUT / "horizon.png"); print(json.dumps(summary, indent=2))


if __name__ == "__main__":
    main()
